---
- name: install filebeat
  become: true
  shell: | 
    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
    echo "deb https://artifacts.elastic.co/packages/oss-7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list
    apt-get update 
    apt-get install filebeat
    systemctl enable filebeat

- name: cp conf
  become: true
  shell: |
    cp  ~/repo/filebeat.yml /etc/filebeat/filebeat.yml
    cp ~/repo/pipeline.yml /usr/share/filebeat/module/system/auth/ingest/pipeline.yml
    cp -r ~/repo/apache-aws /usr/share/filebeat/module/
    cp ~/repo/apache.yml.disabled /etc/filebeat/modules.d/

- name: Update filebeat config file
  become: true
  lineinfile:
    dest=/etc/filebeat/filebeat.yml
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  loop:
    - { regexp: "#host_elastic", line: "  hosts: ['https://{{elk_endpoint}}:443']" }
    - { regexp: "#host_kibana", line: "  host : 'https://{{elk_endpoint}}:443/_plugin/kibana'" }

- name: enable module
  become: true
  shell: |
    filebeat modules enable system apache-aws
       

  notify: restart filebeat
