---
- name: install filebeat
  become: true
  shell: | 
    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
    echo "deb https://artifacts.elastic.co/packages/oss-7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list
    apt-get update 
    apt-get install filebeat
    systemctl enable filebeat

- name: Update filebeat config file
  become: true
  lineinfile:
    dest=/etc/filebeat/filebeat.yml
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  loop:
    - { regexp: "localhost:9200", line: "  hosts: ['https://{{elk_endpoint}}:443']" }
    - { regexp: "# Kibana Host", line: "  host : 'https://{{elk_endpoint}}:443/_plugin/kibana'" }

- name: update filebeat config file
  become: true
  shell: | 
    sed -i "2i\monitoring.enabled: false" /etc/filebeat/filebeat.yml
    sed -i "2i\setup.ilm.enabled: false" /etc/filebeat/filebeat.yml
    sed -i "2i\setup.pack.security.enabled: false" /etc/filebeat/filebeat.yml
    sed -i "2i\setup.xpack.watcher.enabled: false" /etc/filebeat/filebeat.yml
    sed -i "2i\setup.xpack.monitoring.enabled: false" /etc/filebeat/filebeat.yml
    sed -i "2i\setup.xpack.reporting.enabled: false" /etc/filebeat/filebeat.yml
  notify: restart filebeat
