---
- name: install java
  become: true
  shell: |
    apt install openjdk-11-jre-headless
    export JAVA_HOME="usr/lib/jvm/java-11-openjdk-amd64"

- name: install logstash
  become: true
  shell: | 
    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
    echo "deb https://artifacts.elastic.co/packages/oss-7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list
    apt-get update 
    apt-get install logstash
