---
- name: apt install logstash
  become: true
  shell: |
    apt-get -y install default-jre
    apt-get -y install logstash
- name: cp conf
  become: true
  shell: 
    cp -r ~/repo/apache.conf /etc/logstash/conf.d/apache.conf


- name: start
  become: true
  shell:
    /usr/share/logstash/bin/logstash -f /etc/logstash/conf.d/apache.conf


- name: Update logstash config file
  become: true
  lineinfile:
    dest=/etc/logstash/conf.d/apache.conf
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  loop:
    - { regexp: "#host_elastic", line: "    hosts => ['https://{{elk_endpoint}}:443']" }  
