---
- name: Install OpenJDK Java
  become: yes
  apt: name=openjdk-8-jdk update_cache=yes

- name: apt install logstash
  become: true
  shell: | 
    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
    echo "deb https://artifacts.elastic.co/packages/oss-7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list
    apt-get update 
    apt-get -y install logstash
  notify: restart logstash
