---
- name: Download WordPress  
  get_url:
    url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no
  become: true


- name: Extract WordPress  
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no
  become: true

- name: Update default Apache site
  become: true
  lineinfile:
    dest=/etc/apache2/sites-enabled/your_domain.conf
    regexp="(.)+DocumentRoot /var/www/html"
    line="DocumentRoot /var/www/wordpress"
  notify: restart apache

