
---
- name: Download WordPress  
  get_url:
    url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no
  become: true


- name: Extract WordPress  
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no
  become: true

- name: Update default Apache site
  become: true
  lineinfile:
    dest=/etc/apache2/sites-enabled/000-default.conf
    regexp="(.)+DocumentRoot /var/www/html"
    line="DocumentRoot /var/www/wordpress"
  notify: restart apache

- name: Copy sample config file
  command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php creates=/var/www/wordpress/wp-config.php
  become: true

- name: update wordpress config file to set cookies directory
  become: true
  shell: | 
    sed -i "2i\$_SERVER['HTTPS']='on';" /var/www/wordpress/wp-config.php
    sed -i "2i\define('FORCE_SSL_ADMIN', true);" /var/www/wordpress/wp-config.php

- name: Update WordPress config file
  become: true
  lineinfile:
    dest=/var/www/wordpress/wp-config.php
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  loop:
    - { regexp: "define\\( 'DB_NAME', '(.)+' \\);", line: "define( 'DB_NAME', '{{wp_mysql_db}}');" }
    - { regexp: "define\\( 'DB_USER', '(.)+' \\);", line: "define( 'DB_USER', '{{wp_mysql_user}}');" }
    - { regexp: "define\\( 'DB_PASSWORD', '(.)+' \\);", line: "define( 'DB_PASSWORD', '{{wp_mysql_pwd}}');" }
    - { regexp: "define\\( 'DB_HOST', '(.)+' \\);", line: "define( 'DB_HOST', '{{wp_mysql_host}}');" }    
  notify: restart apache
