---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600 
  become: true 

- name: Install required software
  apt: name={{ item }} update_cache=yes state=latest
  loop: [ 'apache2', 'mysql-server', 'python3-pymysql', 'php', 'php-mysql', 'libapache2-mod-php' ]
  become: true
