---
- name: install metricbeat
  become: true
  shell: | 
    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
    echo "deb https://artifacts.elastic.co/packages/oss-7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list
    apt-get update 
    apt-get install metricbeat
    metricbeat modules enable system

    systemctl enable metricbeat

- name: cp conf
  become: true
  shell: 
    cp -r ~/repo/metricbeat.yml /etc/metricbeat/metricbeat.yml

- name: Update metricbeat config file
  become: true
  lineinfile:
    dest=/etc/metricbeat/metricbeat.yml
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  loop:
    - { regexp: "#host_elastic", line: "  hosts: ['https://{{elk_endpoint}}:443']" }
    - { regexp: "#host_kibana", line: "  host : 'https://{{elk_endpoint}}:443/_plugin/kibana'" }
  notify: restart metricbeat    
