---
- name: download php memcached client
  become: true
  shell: |
    wget https://elasticache-downloads.s3.amazonaws.com/ClusterClient/PHP-7.2/latest-64bit
    tar -zxvf latest-64bit
    cp amazon-elasticache-cluster-client.so /usr/lib/php/20170718
    echo "extension=amazon-elasticache-cluster-client.so" | sudo tee --append /etc/php/7.2/apache2/php.ini
  notify: restart apache
  tags: test
    
- name: install plugin w3 total cache
  become: true
  shell: |
    chmod 777 wp-content
    wp plugin install w3-total-cache --activate --allow-root
    wp w3-total-cache fix_environment --allow-root
    chmod 755 wp-content
  args:
    chdir: "/var/www/wordpress"
  notify: restart apache
  tags: test


- name: configure plugin w3 total cache
  become: true
  shell: |
    chmod 777 /var/www/wordpress/wp-content/w3tc-config
    chmod 777 /var/www/wordpress/wp-content/cache
    wp w3-total-cache option set dbcache.enabled true --type=boolean --allow-root
    wp w3-total-cache option set dbcache.engine "memcached"  --allow-root
    wp w3-total-cache option set dbcache.memcached.servers {{memcached_server}}  --allow-root    
    chmod 755 wp-content /var/www/wordpress/wp-content/w3tc-config
    chmod 755 /var/www/wordpress/wp-content/cache  
  args:
    chdir: "/var/www/wordpress"
  notify: restart apache
  tags: test

