---    
- name: install plugin w3 statistic 
  become: true
  shell: |
    chmod 777 wp-content
    wp plugin install user-activity-log --activate --allow-root
    chmod 755 wp-content
  args:
    chdir: "/var/www/wordpress"
  notify: restart apache
